### ISSUE TITLE
failure running the todomvc example 

### ISSUE THREAD

**Issue by nrfm** [arachne-framework/factui#3]
Hi, trying to run the example as per the readme...

```
$ lein figwheel
Figwheel: Cleaning because dependencies changed
Figwheel: Cutting some fruit, just a sec ...
Could not find artifact org.arachne-framework:factui:jar:1.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)
...
```

am i missing something?
thanks!

**Comment by levand** [comment]
Looks like you need clone the FactUI codebase and run `lein install` in the FactUI source directory, to get `1.1.0-SNAPSHOT` installed to your local maven repo. I should get a release version deployed to clojars so that isn't necessary, but it will get you running for now.

**Comment by nrfm** [comment]
thanks for the quick response! 👍 will do that.
